# Generated by Django 5.1.6 on 2025-02-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_active',
            new_name='status',
        ),
    ]
