# Generated by Django 5.1.6 on 2025-03-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0003_alter_users_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
