# Generated by Django 5.1.6 on 2025-04-03 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0005_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('approver_role', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'approval_steps',
                'ordering': ['order'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('latex_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_workflow', models.ManyToManyField(to='ums.approvalstep')),
            ],
            options={
                'db_table': 'document_templates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('context_data', models.JSONField(default=dict)),
                ('current_state', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('returned', 'Returned for Changes'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ums_created_documents', to='ums.users')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ums.approvalstep')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ums_signed_documents', to='ums.users')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.documenttemplate')),
            ],
            options={
                'db_table': 'generated_documents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_data', models.TextField()),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('return', 'Return for Changes')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.approvalstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ums_document_signatures', to='ums.users')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ums_signatures', to='ums.generateddocument')),
            ],
            options={
                'db_table': 'document_signatures',
                'managed': True,
            },
        ),
    ]
