# Generated by Django 5.1.6 on 2025-04-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0006_approvalstep_documenttemplate_generateddocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Basicuser', 'Basic User')], default='Basicuser', max_length=100),
        ),
    ]
