# Generated by Django 5.1.6 on 2025-04-03 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0007_alter_users_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsignature',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='is_chair_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='decision',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('return', 'Return for Changes'), ('pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='ums.generateddocument'),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.users'),
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone'), ('file', 'File Upload'), ('signature', 'Signature')], max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='ums.documenttemplate')),
            ],
            options={
                'db_table': 'template_fields',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
