# Generated by Django 5.1.6 on 2025-04-03 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0009_documenttemplate_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsignature',
            name='approval_step',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='approval_workflow',
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='templatefield',
            name='template',
        ),
        migrations.AlterModelOptions(
            name='documentsignature',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generateddocument',
            options={},
        ),
        migrations.RenameField(
            model_name='documentsignature',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='documentsignature',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='documentsignature',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='documentsignature',
            name='is_chair_signature',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='template_type',
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='current_state',
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='signed_at',
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.generateddocument'),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ums.users'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='latex_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to='ums.users'),
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='signed_by',
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ums.documenttemplate'),
        ),
        migrations.AlterModelTable(
            name='documentsignature',
            table=None,
        ),
        migrations.AlterModelTable(
            name='documenttemplate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='generateddocument',
            table=None,
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=60)),
                ('comments', models.TextField(blank=True, null=True)),
                ('time_approved', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.users')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.generateddocument')),
            ],
        ),
        migrations.CreateModel(
            name='RCEForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('semester', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.users')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCircumstanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=10)),
                ('graduation_date', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('special_request_type', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.users')),
            ],
        ),
        migrations.DeleteModel(
            name='ApprovalStep',
        ),
        migrations.DeleteModel(
            name='TemplateField',
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='signed_by',
            field=models.ManyToManyField(through='ums.DocumentSignature', to='ums.users'),
        ),
    ]
