# Generated by Django 5.1.6 on 2025-04-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0010_remove_documentsignature_approval_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rceform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='rceform',
            name='decision',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10, null=True),
        ),
    ]
