# Generated by Django 5.1.6 on 2025-04-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0012_specialcircumstanceform_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttemplate',
            old_name='latex_content',
            new_name='html_content',
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
