# Generated by Django 5.1.6 on 2025-04-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0013_rename_latex_content_documenttemplate_html_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(upload_to='admin_signatures/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_signatures', to='ums.users')),
            ],
            options={
                'unique_together': {('admin', 'is_active')},
            },
        ),
    ]
