# Generated by Django 5.1.6 on 2025-04-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0014_adminsignature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentapproval',
            name='time_approved',
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
