# Generated by Django 5.1.6 on 2025-04-19 19:32

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0015_remove_documentapproval_time_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentapproval',
            name='is_org_level_approval',
            field=models.BooleanField(default=False, help_text='Whether this is an organizational-level approval'),
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ums.organizationalunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='organizational_unit',
            field=models.ForeignKey(blank=True, help_text='The organizational unit context for this approval', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ums.organizationalunit'),
        ),
        migrations.AddField(
            model_name='rceform',
            name='organizational_unit',
            field=models.ForeignKey(help_text='The organizational unit this request belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ums.organizationalunit'),
        ),
        migrations.AddField(
            model_name='specialcircumstanceform',
            name='organizational_unit',
            field=models.ForeignKey(help_text='The organizational unit this request belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ums.organizationalunit'),
        ),
        migrations.CreateModel(
            name='UserOrganizationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approver', models.BooleanField(default=False, help_text='Whether the user can approve requests for this unit')),
                ('is_organizational_approver', models.BooleanField(default=False, help_text='Whether the user can approve requests across multiple units')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.organizationalunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.users')),
            ],
            options={
                'ordering': ('organizational_unit__name', 'user__name'),
                'unique_together': {('user', 'organizational_unit')},
            },
        ),
        migrations.AddField(
            model_name='users',
            name='organizational_units',
            field=models.ManyToManyField(related_name='users', through='ums.UserOrganizationAssignment', to='ums.organizationalunit'),
        ),
    ]
