# Generated by Django 5.1.6 on 2025-04-21 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0016_documentapproval_is_org_level_approval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermWithdrawalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myuh_id', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('program_plan', models.CharField(max_length=100)),
                ('academic_career', models.CharField(max_length=50)),
                ('withdrawal_term', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=10)),
                ('withdrawal_year', models.IntegerField()),
                ('financial_aid_acknowledged', models.BooleanField(default=False)),
                ('international_student_acknowledged', models.BooleanField(default=False)),
                ('student_athlete_acknowledged', models.BooleanField(default=False)),
                ('veteran_acknowledged', models.BooleanField(default=False)),
                ('graduate_student_acknowledged', models.BooleanField(default=False)),
                ('doctoral_student_acknowledged', models.BooleanField(default=False)),
                ('housing_acknowledged', models.BooleanField(default=False)),
                ('dining_services_acknowledged', models.BooleanField(default=False)),
                ('parking_acknowledged', models.BooleanField(default=False)),
                ('final_acknowledgment', models.BooleanField(default=False)),
                ('signature_data', models.TextField(blank=True)),
                ('signature_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('organizational_unit', models.ForeignKey(help_text='The organizational unit this request belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ums.organizationalunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.users')),
            ],
        ),
    ]
