# Generated by Django 5.1.6 on 2025-04-21 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0016_documentapproval_is_org_level_approval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('delegatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_delegations', to='ums.users')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegated_approvals', to='ums.users')),
            ],
        ),
    ]
