# Generated by Django 5.1.6 on 2025-04-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0017_approvaldelegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldelegation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
