# Generated by Django 5.1.6 on 2025-04-22 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0017_termwithdrawalform'),
        ('ums', '0018_approvaldelegation_active'),
    ]

    operations = [
    ]
