# Generated by Django 5.1.6 on 2025-04-22 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0019_merge_20250421_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaldelegation',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VeteranCertificationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('academic_career', models.CharField(choices=[('UGRD', 'UGRD'), ('GRAD', 'GRAD')], max_length=10)),
                ('va_chapter', models.CharField(choices=[('Chapter 31', 'Chapter 31'), ('Chapter 33', 'Chapter 33')], max_length=20)),
                ('va_counselor_email', models.EmailField(max_length=254)),
                ('va_authorization_no', models.CharField(max_length=50)),
                ('intended_major', models.CharField(blank=True, max_length=100)),
                ('first_time_using', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('certified_hours', models.IntegerField()),
                ('final_semester', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('organizational_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ums.organizationalunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.users')),
            ],
        ),
    ]
