# Generated by Django 5.1.6 on 2025-04-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0020_alter_approvaldelegation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
