# Generated by Django 5.1.6 on 2025-04-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0021_organizationalunit_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalunit',
            name='code',
        ),
        migrations.AddField(
            model_name='veterancertificationform',
            name='decision',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10, null=True),
        ),
    ]
