
services:
  web:
    build: .
    command: gunicorn moosejawums.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MooseJawSD314
      MYSQL_DATABASE: mjapp
      MYSQL_USER: MooseJawAdmin
      MYSQL_PASSWORD: MooseJawSD314
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
