import os
import django
import uuid
import json

# Set up Django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "moosejawums.settings")
django.setup()

# Import models
from pdfdocs.models import DocumentTemplate, GeneratedDocument, DocumentSignature
from ums.models import Users

# Get test user
user = Users.objects.get(id='test123')
print(f"Using user: {user.name} (ID: {user.id})")

# Get or create test template
template, created = DocumentTemplate.objects.get_or_create(
    name="Test Template",
    defaults={
        'description': "A simple test template",
        'latex_content': "\\documentclass[12pt]{article}..."  # Shortened for brevity
    }
)

print(f"Using template: {template.name}")

# Register the generated PDF in the database
document = GeneratedDocument.objects.create(
    title="Test Document",
    template=template,
    created_by=user,
    file_path="pdfs/test_document.pdf",
    context_data={
        'document_id': "12345",
        'document_title': "Test Document",
        'user_name': user.name,
        'user_email': user.email,
        'generation_date': "2025-03-18",
        'custom_text': "This is a test document generated by the PDF generation system."
    }
)

print(f"Document registered in database with ID: {document.id}")
print(f"File path: {document.file_path}")